{% set name = "sugartex" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e14ffbef643b34d6d4cb0de5b57d55e58f16a9afbe7e18e99ab4e33a4f92dd30

build:
  noarch: python
  number: 0
  entry_points:
    - sugartex = sugartex.sugartex_pandoc_filter:cli
    - pre-sugartex = sugartex.pre_sugartex:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - panflute >=1.11.2

test:
  imports:
    - sugartex
  commands:
    - sugartex --help
    - pre-sugartex --help

about:
  home: https://github.com/kiwi0fruit/sugartex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "More readable LaTeX language extension and transcompiler to LaTeX"
  doc_url: https://github.com/kiwi0fruit/sugartex
  dev_url: https://github.com/kiwi0fruit/sugartex

extra:
  recipe-maintainers:
    - kiwi0fruit
