#!/bin/bash
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

tagname="0.1.16"
git tag -d "$tagname"
git push --delete origin "$tagname"
git tag -a "$tagname"
git push --tags

python setup.py sdist
if [[ "$(uname -s)" == MINGW* ]]; then
    winpty twine upload dist/* --skip-existing
else
    twine upload dist/* --skip-existing; fi

rm -rf ./dist
